import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const output = resolve(root, 'src/client/generated/art.ts')
const assets = [
  ['LANYIN_HARBOR_ART', 'assets/lanyin-harbor.jpg', 'image/jpeg'],
  ['TEAHOUSE_HARBOR_ART', 'assets/teahouse-harbor-v2.jpg', 'image/jpeg'],
  ['TEAHOUSE_GAMES_ART', 'assets/teahouse-games-v2.jpg', 'image/jpeg'],
]
const source = [
  '/** Generated by scripts/embed-assets.mjs. Do not edit by hand. */',
  ...await Promise.all(assets.map(async ([name, assetPath, mime]) => {
    const bytes = await readFile(resolve(root, assetPath))
    return `export const ${name} = ${JSON.stringify(`data:${mime};base64,${bytes.toString('base64')}`)}`
  })),
  '',
].join('\n')

await mkdir(dirname(output), { recursive: true })
await writeFile(output, source)
