import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const output = resolve(root, 'src/client/generated/art.ts')

const artwork = [
  ['LANYIN_CALM_ART', 'assets/lanyin-harbor.jpg'],
  ['LANYIN_THINKING_ART', 'assets/lanyin-thinking.jpg'],
  ['LANYIN_PLEASED_ART', 'assets/lanyin-pleased.jpg'],
  ['LANYIN_CONCERNED_ART', 'assets/lanyin-concerned.jpg'],
]

const declarations = await Promise.all(artwork.map(async ([name, path]) => {
  const bytes = await readFile(resolve(root, path))
  const dataUrl = `data:image/jpeg;base64,${bytes.toString('base64')}`
  return `export const ${name} = ${JSON.stringify(dataUrl)}`
}))

const source = [
  '/** Generated by scripts/embed-assets.mjs. Do not edit by hand. */',
  ...declarations,
  '',
  '/** Backwards-compatible name for the original calm harbor artwork. */',
  'export const LANYIN_HARBOR_ART = LANYIN_CALM_ART',
  '',
].join('\n')

await mkdir(dirname(output), { recursive: true })
await writeFile(output, source)
