import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const input = resolve(root, 'assets/lanyin-harbor.jpg')
const output = resolve(root, 'src/client/generated/art.ts')
const bytes = await readFile(input)
const source = [
  '/** Generated by scripts/embed-assets.mjs. Do not edit by hand. */',
  `export const LANYIN_HARBOR_ART = ${JSON.stringify(`data:image/jpeg;base64,${bytes.toString('base64')}`)}`,
  '',
].join('\n')

await mkdir(dirname(output), { recursive: true })
await writeFile(output, source)

